server:
  port: 8182
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '0786'
    url: jdbc:mysql://localhost:3306/spring-boot-one-to-one-bi
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
